# fly.toml app configuration file generated for my-store-app on 2023-10-19T13:24:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-store-app"
primary_region = "scl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = '3000'
